# templates/rolebinding-frontend.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-rolebinding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: {{ .Values.frontend.serviceAccount.name }}
    namespace: dev
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io