# templates/rolebinding-backend.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backend.serviceAccount.name }}
    namespace: dev
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io