replicaCount: 2

image:
  repository: bansikah/random-group-generator
  tag: "1.1"
  pullPolicy: IfNotPresent
  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 5000

service:
  type: NodePort
  port:
  - protocol: TCP
    port: 80
    targetPort: 5000

ingress:
  enabled: true
  host: random-group-generator.local
  path: /