#values-prod.yaml shop app
environment: prod 

frontend:
  image:
    repository: bansikah/shop-frontend
    tag: "1.2.2"
  replicaCount: 2
  pullPolicy: IfNotPresent
  env:
    REACT_APP_API_URL: "https://shop-app-prod.bansikah.ip-dynamic.org/api"
  ports:
    - containerPort: 80
  nodeSelector:
    role: worker  

backend:
  image:
    repository: bansikah/shop-backend
    tag: "1.2.2"
  replicaCount: 2
  pullPolicy: IfNotPresent
  nodeSelector:
    role: worker  

postgres:
  image:
    repository: postgres
    tag: latest
  database: shopdb
  username: postgresuser
  password: postgrespass
  nodeSelector:
    role: worker  

ingress:
  host: shop-app-prod.bansikah.ip-dynamic.org
